### ISSUE TITLE
Add a task in package.json to export chrome extension components

### ISSUE THREAD

**Issue by ashwanthkumar** [praneshr/livewire#1]
Once the app CSS and JS are compiled we just need the following
- index.html
- build/main.*
- js/*.js
- background.html
- manifest.json

If we could copy all them into a separate folder - even inside the `build/`. This helps reduce the size of the crx file for the users. 

Also, can we please not publish the build/ folder into the repo? The 1MB takes a toll while cloning the repo.

**Comment by praneshr** [comment]
@ashwanthkumar Get a pull and try to build it. :)

**Comment by praneshr** [comment]
Created webpack tasks to handle file moving.

**Comment by ashwanthkumar** [comment]
Can you add that as a section on the README?

On Tue, Jun 30, 2015 at 11:57 AM, Pranesh Ravi notifications@github.com
wrote:

> Closed #1 https://github.com/praneshr/livewire/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/praneshr/livewire/issues/1#event-343836010.

## 

Ashwanth Kumar / ashwanthkumar.in
